---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: pgo
  namespace: flux-system
spec:
  interval: 5m0s
  url: oci://registry.developers.crunchydata.com/crunchydata/pgo
  ref:
    semver: "*"
