---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway-crds
  namespace: flux-system
spec:
  interval: 24h
  url: oci://cr.kgateway.dev/kgateway-dev/charts/kgateway-crds
  ref:
    tag: v2.0.4
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway
  namespace: flux-system
spec:
  interval: 24h
  url: oci://cr.kgateway.dev/kgateway-dev/charts/kgateway
  ref:
    tag: v2.0.4
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway-crds
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: kgateway-system
  storageNamespace: kgateway-system
  releaseName: kgateway-crds
  install:
    createNamespace: true
  chartRef:
    kind: OCIRepository
    name: kgateway-crds
    namespace: flux-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: kgateway-system
  storageNamespace: kgateway-system
  releaseName: kgateway
  install:
    createNamespace: true
  chartRef:
    kind: OCIRepository
    name: kgateway
    namespace: flux-system
