---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubescape
  namespace: flux-system
spec:
  interval: 24h
  url: https://kubescape.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubescape
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: kubescape
  storageNamespace: kubescape
  releaseName: kubescape-operator
  install:
    createNamespace: true
  chart:
    spec:
      chart: kubescape-operator
      version: 1.29.8
      sourceRef:
        kind: HelmRepository
        name: kubescape
        namespace: flux-system
  values:
    clusterName: homelab-rke2
    capabilities:
      continuousScan: enable
