---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  interval: 24h
  timeout: 5m
  ref:
    tag: v1.3.0
  url: https://github.com/kubernetes-sigs/gateway-api
